# Generated by Django 3.1.2 on 2021-12-26 07:55

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='answer',
            name='date_posted',
            field=models.DateTimeField(default=datetime.datetime(2021, 12, 26, 13, 25, 56, 115299)),
        ),
        migrations.AlterField(
            model_name='answer',
            name='image',
            field=models.ImageField(default=None, upload_to='mainapp/question_images/'),
        ),
        migrations.AlterField(
            model_name='question',
            name='image',
            field=models.ImageField(default=None, upload_to='mainapp/question_images/'),
        ),
    ]
