# Generated by Django 3.1.2 on 2021-12-26 12:57

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_auto_20211226_1331'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='graduation_year',
            field=models.IntegerField(default=2023),
        ),
        migrations.AlterField(
            model_name='answer',
            name='date_posted',
            field=models.DateTimeField(default=datetime.datetime(2021, 12, 26, 18, 27, 7, 106003)),
        ),
    ]
