# Generated by Django 4.0 on 2021-12-26 16:04

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_alter_answer_date_posted_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='answer',
            name='date_posted',
            field=models.DateTimeField(default=datetime.datetime(2021, 12, 26, 16, 4, 30, 184592)),
        ),
        migrations.AlterField(
            model_name='internship',
            name='date_posted',
            field=models.DateTimeField(default=datetime.datetime(2021, 12, 26, 16, 4, 30, 185969)),
        ),
        migrations.AlterField(
            model_name='job',
            name='date_posted',
            field=models.DateTimeField(default=datetime.datetime(2021, 12, 26, 16, 4, 30, 185441)),
        ),
    ]
