# Generated by Django 4.0 on 2021-12-26 16:17

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_alter_answer_date_posted_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='answer',
            name='date_posted',
            field=models.DateTimeField(default=datetime.datetime(2021, 12, 26, 16, 17, 57, 286215)),
        ),
        migrations.AlterField(
            model_name='internship',
            name='date_posted',
            field=models.DateField(default=datetime.datetime(2021, 12, 26, 16, 17, 57, 287122)),
        ),
        migrations.AlterField(
            model_name='internship',
            name='position',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='job',
            name='date_posted',
            field=models.DateField(default=datetime.datetime(2021, 12, 26, 16, 17, 57, 286754)),
        ),
        migrations.AlterField(
            model_name='job',
            name='position',
            field=models.CharField(max_length=30),
        ),
    ]
