# Generated by Django 3.1.2 on 2021-12-26 17:31

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('main', '0010_alter_answer_date_posted_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='answer',
            name='date_posted',
            field=models.DateTimeField(default=datetime.datetime(2021, 12, 26, 23, 1, 3, 931460)),
        ),
        migrations.AlterField(
            model_name='internship',
            name='date_posted',
            field=models.DateField(default=datetime.datetime(2021, 12, 26, 23, 1, 3, 932496)),
        ),
        migrations.AlterField(
            model_name='job',
            name='date_posted',
            field=models.DateField(default=datetime.datetime(2021, 12, 26, 23, 1, 3, 931460)),
        ),
        migrations.CreateModel(
            name='Referral',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(max_length=500)),
                ('position', models.CharField(max_length=30)),
                ('job_id', models.CharField(max_length=100)),
                ('link', models.URLField()),
                ('status', models.BooleanField(default=False)),
                ('date_posted', models.DateField(default=datetime.datetime(2021, 12, 26, 23, 1, 3, 932496))),
                ('posted_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
